### ISSUE TITLE
Is the Cypress base url environment variable correct in the provided configuration?

### ISSUE THREAD

**Issue by kinow** [cypress-io/cypress-gh-action-vue-example#2]
Hi,

I have added the cypress github action to our current workflow in a pull request. It failed several times, until testing locally I found that if I used `export CYPRESS_baseUrl=http://localhost:8080/` my tests failed locally with a timeout error (same as in GitHUb workflow).

But if instead I used `export CYPRESS_BASE_URL=http://localhost:8080/`, then it worked. The PR's workflow is now [passing](https://github.com/cylc/cylc-ui/pull/423).

I tried that after finding that variable in the Cypress [docs](https://docs.cypress.io/guides/guides/environment-variables.html).

![image](https://user-images.githubusercontent.com/304786/76475638-72938880-6464-11ea-8f15-0f04d42045e9.png)

Thanks
Bruno

**Comment by bahmutov** [comment]
Not sure where you saw the problem. I see in your commit https://github.com/cylc/cylc-ui/pull/423/commits/3f8f723008cb3af390828e042e9cd52f98fe9f3b `CYPRESS_baseUrl` and it did pass the tests https://github.com/cylc/cylc-ui/runs/501890221

**Comment by kinow** [comment]
> 
> 
> Not sure where you saw the problem. I see in your commit [cylc/cylc-ui@3f8f723](https://github.com/cylc/cylc-ui/commit/3f8f723008cb3af390828e042e9cd52f98fe9f3b) `CYPRESS_baseUrl` and it did pass the tests https://github.com/cylc/cylc-ui/runs/501890221

Eerr. Sorry @bahmutov , just rebased my commit and pushed again, and it indeed passed without the need to rename that variable.

I think I didn't see that the previous commit had fixed it, and then got confused by which commit had fixed it. Closing! Sorry about the noise.

Thanks

**Comment by bahmutov** [comment]
No worries, glad you find Cypress GH Action useful
